import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createApp,TITLES,validateResult} from './server.mjs';
const fixture=()=>({modules:TITLES.map((title,i)=>({number:i+1,title,content:'| Campo | Saída |\n| --- | --- |\n| Exemplo | NÃO INFORMADO |'})),pending:[]});
async function withServer(options,fn){const s=createApp(options);await new Promise(r=>s.listen(0,'127.0.0.1',r));try{await fn('http://127.0.0.1:'+s.address().port);}finally{await new Promise(r=>s.close(r));}}
const env={OPENAI_API_KEY:'test-key',APP_ACCESS_CODE:'test-access'};
test('servidor serve interface sem expor regras ou segredos',async()=>withServer({env},async base=>{const r=await fetch(base);assert.equal(r.status,200);assert.match(r.headers.get('content-security-policy'),/frame-ancestors 'none'/);assert.match(await r.text(),/Módulos do cadastro/);assert.equal((await fetch(base+'/regras/modulos.md')).status,404);assert.equal((await fetch(base+'/.env')).status,404);}));
test('configuração ausente impede análise',async()=>withServer({env:{}},async base=>{assert.equal((await fetch(base+'/api/analyze',{method:'POST'})).status,503);}));
test('autorização e tipo de arquivo antes de chamar IA',async()=>withServer({env,fetcher:()=>{throw Error('Não deveria chamar IA');}},async base=>{assert.equal((await fetch(base+'/api/analyze',{method:'POST'})).status,401);assert.equal((await fetch(base+'/api/analyze',{method:'POST',headers:{Authorization:'Bearer test-access','Content-Type':'text/plain'},body:'abc'})).status,415);assert.equal((await fetch(base+'/api/analyze',{method:'POST',headers:{Authorization:'Bearer test-access','Content-Type':'application/pdf'},body:'texto'})).status,415);}));
test('envia PDF, regras atuais e metadados, devolvendo 19 módulos',async()=>{let captured;await withServer({env,fetcher:async(url,options)=>{captured=JSON.parse(options.body);return new Response(JSON.stringify({status:'completed',output:[{content:[{type:'output_text',text:JSON.stringify(fixture()),annotations:[]}]}]}));}},async base=>{const r=await fetch(base+'/api/analyze',{method:'POST',headers:{Authorization:'Bearer test-access','Content-Type':'application/pdf','X-Receipt-Date':'2026-10-08','X-Client-Code':'123'},body:'%PDF-1.4\nmock'});assert.equal(r.status,200);assert.equal((await r.json()).modules.length,19);assert.equal(captured.store,false);assert.match(captured.input[0].content[1].file_data,/^data:application\/pdf;base64,/);assert.match(captured.instructions,/SOMENTE DA SEÇÃO FINAL/);assert.match(captured.instructions,/SEM AUDIÊNCIA DESIGNADA AO CADASTRAR/);assert.match(captured.input[0].content[0].text,/2026-10-08/);});});
test('data inválida e origem externa são rejeitadas',async()=>withServer({env},async base=>{const headers={Authorization:'Bearer test-access','Content-Type':'application/pdf','X-Receipt-Date':'2026-02-31'};assert.equal((await fetch(base+'/api/analyze',{method:'POST',headers,body:'%PDF-1.4'})).status,400);assert.equal((await fetch(base+'/api/analyze',{method:'POST',headers:{...headers,Origin:'https://externo.example'},body:'%PDF-1.4'})).status,403);}));
test('respostas incompletas ou fora da ordem são rejeitadas',()=>{assert.throws(()=>validateResult({...fixture(),modules:[]}));const bad=fixture();bad.modules[0].number=2;assert.throws(()=>validateResult(bad));assert.equal(validateResult(fixture()).modules.length,19);});
